bstar-b-a: Makefile bstar-b-a.cpp ../../include/types.h ../../include/util.h ../../util/util.cpp Makefile
	g++ -DBSTAR_B_A_SUFFIX_SORT_MAIN -I ../../include/ -O3 -Wall bstar-b-a.cpp ../../util/util.cpp -o bstar-b-a
