simple-suffix-sort: Makefile suffix-sort.cpp ../../include/types.h ../../include/util.h ../../util/util.cpp Makefile
	g++ -DSIMPLE_SUFFIX_SORT_MAIN -I ../../include/ -O3 -Wall suffix-sort.cpp ../../util/util.cpp -o simple-suffix-sort

